dist: bionic
language: node_js
node_js:
- 12

addons:
  apt:
    packages:
      - pulseaudio

env:
  matrix:
    - BROWSER=chrome  BVER=stable

matrix:
  fast_finish: true

before_script:
  - ./node_modules/travis-multirunner/setup.sh
  - pulseaudio --start
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test && npm run test-travis

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

